version: '3.7'

services:
  node:
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=fluentdispatch
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/fluentdispatch.pfx
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https/
  cluster:
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=fluentdispatch
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/fluentdispatch.pfx
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https/