version: "3.7"
services:
  node:
    container_name: fluentdispatch-node
    environment:
      FLUENTDISPATCH_NODE_LISTENING_PORT: 9090
      ELASTICSEARCH_ENDPOINT: "http://elasticsearch:9200"
    build:
      context: ../../
      dockerfile: Samples/Remote/FluentDispatch.Node/Dockerfile
    image: fluentdispatch/node:v1
    ports:
      - "9090:9090"
    networks:
      - fluentdispatch-network
  cluster:
    container_name: fluentdispatch-cluster
    environment:
      INFLUXDB_ENDPOINT: "http://influxdb:8086"
      INFLUXDB_DATABASE: "fluentdispatch"
      FLUENTDISPATCH_CLUSTER_LISTENING_PORT: 5432
      FLUENTDISPATCH_CLUSTER_NODES: "[{'MachineName':'node','Port':9090}]"
    build:
      context: ../../
      dockerfile: Samples/Remote/FluentDispatch.Cluster/Dockerfile
    image: fluentdispatch/cluster:v1
    depends_on:
      - node
    ports:
      - "5432:5432"
    networks:
      - fluentdispatch-network
  grafana:
    build: './grafana'
    container_name: fluentdispatch-grafana
    restart: always
    image: grafana
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_INSTALL_PLUGINS: "grafana-piechart-panel"
    depends_on:
      - influxdb
    volumes:
      - grafana-volume:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - fluentdispatch-network
  influxdb:
    container_name: fluentdispatch-influxdb
    image: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb-volume:/var/lib/influxdb
    networks:
      - fluentdispatch-network
  elasticsearch:
    container_name: fluentdispatch-elasticsearch
    build:
      context: elk/elasticsearch/
      args:
        ELK_VERSION: "7.4.1"
    image: elasticsearch
    volumes:
      - type: bind
        source: ./elk/elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch-volume
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: admin
    networks:
      - fluentdispatch-network
  logstash:
    container_name: fluentdispatch-logstash
    build:
      context: elk/logstash/
      args:
        ELK_VERSION: "7.4.1"
    image: logstash
    volumes:
      - type: bind
        source: ./elk/logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./elk/logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - fluentdispatch-network
    depends_on:
      - elasticsearch
  kibana:
    container_name: fluentdispatch-kibana
    build:
      context: elk/kibana/
      args:
        ELK_VERSION: "7.4.1"
    image: kibana
    volumes:
      - type: bind
        source: ./elk/kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - fluentdispatch-network
    depends_on:
      - elasticsearch
volumes:
  grafana-volume:
  influxdb-volume:
  elasticsearch-volume:
networks:
  fluentdispatch-network:
    external: false